### ISSUE TITLE
Unreal demo crashes

### ISSUE THREAD

**Issue by GoogleCodeExporter** [tslabs/zx-evo#47]
```
Resets after a while.
```

Original issue reported on code.google.com by `at2...@gmail.com` on 9 Jan 2014 at 9:09

Attachments:
- [UNREAL!.ZIP](https://storage.googleapis.com/google-code-attachments/zx-evo-fpga/issue-47/comment-0/UNREAL!.ZIP)

**Comment by tslabs** [comment]
Fix: remove "No delays" checkbox from Betadisk menu.
