### ISSUE TITLE
Оставшиеся бурсты DMA в отладчике эмулятора показываются в десятичной системе

### ISSUE THREAD

**Issue by Rider1982** [tslabs/zx-evo#62]
В эмуляторе в окне состояния конфы оставшиеся бурсты DMA показываются в десятичной системе, что вызыват когнитивный диссонанс.
![tsemulbug](https://cloud.githubusercontent.com/assets/14853118/10119252/21a44060-6499-11e5-8964-7da13594de9e.png)

**Comment by tslabs** [comment]
Designed intentionally. Replaced by new register window.
