### ISSUE TITLE
Ошибка в размере сохранения

### ISSUE THREAD

**Issue by AlexKorochinskiy** [tslabs/zx-evo#91]
Здравствуйте. В текущей версии ts-bios.asm указан не верный размер сохранения. В строке 1464 указано defs 10     ; dummy, а надо defs 9     ; dummy. Из-за этого при переключении между base conf и ts conf происходит сброс настроек как в ts conf, так и в base conf.

**Comment by AlexKorochinskiy** [comment]
*ts-bios.asm. Извините ошибся с названием файла.

**Comment by tslabs** [comment]
Fixed. Спасибо за репорт.

**Comment by tslabs** [comment]
ที่ตายตัว
